name: Update IPTV Playlist

on:
  schedule:
    - cron: "0 */6 * * *"  # Tự động chạy 6 tiếng một lần
  workflow_dispatch:
  push:
    paths:
      - "update_iptv.py"   # Tự chạy khi cập nhật code

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests

      - name: Set Timezone to Vietnam (ICT)
        run: sudo timedatectl set-timezone Asia/Ho_Chi_Minh

      - name: List files (debug)
        run: |
          echo "Hiện tại là: $(date +'%Y-%m-%d %H:%M:%S %Z')"
          ls -la

      - name: Run IPTV updater
        run: python update_iptv.py

      - name: Get current time
        run: echo "VIETNAM_TIME=$(date +'%d/%m/%Y %H:%M')" >> $GITHUB_ENV

      - name: Commit & push playlist and EPG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 Auto-update IPTV & EPG (${{ env.VIETNAM_TIME }} ICT)"
          file_pattern: "http-iptv.m3u iptv.epg.xml my_list.m3u"
